from aiogram.fsm.state import State, StatesGroup
class Vvod_TradNosh(StatesGroup):
    nazvanijeTrd1=State()
    nazvanijeTrd2 = State()
    nazvanijeTrd3 = State()
    FotoTrd1=State()
    FotoTrd2=State()
    FotoTrd3=State()
    FotoTrd4=State()
    FotoTrd5=State()
    EtnoGrafOpis=State()
    TehnicOpis=State()
    VideoSylka1=State()
    VideoSylka2 = State()
    Prednaz1=State()
    Prednaz2=State()
    Nabrasyvanije1=State()
    Nabrasyvanije2=State()
    Kreplenije1=State()
    Kreplenije2=State()
    EtnoGrafPrin=State()
    GeografPrin=State()